name = "sansar"
uuid = "51ab4694-29f4-451a-acc9-b332852e8762"
authors = ["Avinash Verma <avinash.verma@niser.ac.in> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
